### PR TITLE
When the uri have the slash, the next request should also have the slash

### PR DESCRIPTION
**Pull request by harikt**
Sorry, another case of failure :-) .

### CODE REVIEW

**Comment by harikt** [comment]
#25  , #26 .

**Comment by weierophinney** [comment]
Turns out this is primarily a problem in phly/http, which currently prefixes the path with a "/" if it does not begin with one -- even when empty! Will have a fix for both projects shortly.

**Comment by harikt** [comment]
Yes, that was why I opened https://github.com/phly/http/issues/22 . But I was only able to reproduce it at here.

**Comment by harikt** [comment]
Finally I changed it to use 

```
<?php
$server = $request->getServerParams();
$path = parse_url($server['REQUEST_URI'], PHP_URL_PATH);
```

as `$req->getUri()->getPath()` will return nothing when the request is at `http://example.com`

**Pull request closed without merging**
